{
 "title": "scmscx.com",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "tokio poll latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(le, job) (rate(scmscx_tokio_poll_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "tokio poll rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(le, job) (rate(scmscx_tokio_poll_time_seconds_count[$__rate_interval]))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(scmscx_http_requests_total[$__rate_interval])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "panics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "scmscx_panics_total", "legendFormat": "{{route}}" }
   ]
  },
  {
   "title": "api latency, 95th percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, route, method) (rate(scmscx_http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "pumper pending files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "expr": "scmscx_pumper_pending_files", "legendFormat": "{{route}}" }
   ]
  },
  {
   "title": "pumper uploads, total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "scmscx_pumper_uploads_total", "legendFormat": "{{route}}" }
   ]
  }
 ]
}