name: PR-CI

on:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    timeout-minutes: 30
    name: ${{format('Cargo {0}', matrix.rust)}}
    # if: false
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          # - rust: nightly
          # - rust: beta
          - rust: stable
          # - rust: 1.74.0
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: clippy, rustfmt

      - name: Set up build environment
        uses: ./.github/actions/setup-build-env

      - run: make fmt
      - run: make clippy
      - run: make test
      - run: make scmscx.com-image-debug

      - name: sccache stats
        if: always()
        uses: ./.github/actions/sccache-stats
