name: PR-CI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  test:
    timeout-minutes: 30
    name: ${{format('Cargo {0}', matrix.rust)}}
    # if: false
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        include:
          # - rust: nightly
          # - rust: beta
          - rust: stable
          # - rust: 1.74.0
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
          components: clippy, rustfmt

      - name: work around Cargo.lock filetime not being updated..?
        run: touch Cargo.lock

      - run: ENABLE_GSFS=0 make update
      - run: ENABLE_GSFS=0 make ci
